server:
  port: 8888
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/reactspringblog
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect  #JPA가 사용할 database의 dialect 설정
    #database-platform: org.hibernate.dialect.MariaDB103Dialect  #JPA가 사용할 database의 dialect 설정
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true            #SQL을 보기 좋게 출력
        "[user_sql_comments]": true     #SQL생성 시 주석 포함
        "[highlight_sql]": true         #SQL에 색깔
        "[hbm2ddl.auto]": update        #테이블 자동 생성
        #"[implicit_naming_strategy]": "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy" -> 기본값으로 설정되어 있어서 따로 설정하지 않아도 무방함
    open-in-view: false
    show-sql: true

jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: 9fea599d594fecf14387e72e24529a95c17e1bab614441f13bbfadb871bd32a8df2266c4adfd0bcf9cd2a8d4f4ca8aca48da63a8d5695d97afd4c1eb5fa0a68b  #eyJhbGciOiJIUzUxMiJ9eyJzdWIiOiJ1c2VyIn0I2qOfhAZMGSH1pCecUH5sV2Lg2pSWNQMPzXsMcne6NJ1SlkBoirhGAmKfTYNcRyhu6nQtRzgAd6VXyttoX9A
  tokenExpirationTime: 18000

project:
  folderPath: "files/"
  logging:
    level:
      org:
        apache:
          coyote:
            http11: debug

        hiberante:
          SQL: debug

      boardexample:
        myboard: info